import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import WalletProvider from "../../components/WalletProvider";
import Image from "next/image";
import Link from "next/link";
import WalletConnectButton from "../../components/WalletConnectButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WalletProvider>
          <nav className="w-full flex items-center justify-between px-8 py-6 z-10">
            <Link href="/">
              <Image src="/branding/newlogosnap.svg" alt="Snap Anything Logo" width={160} height={32} priority />
            </Link>
            <WalletConnectButton />
          </nav>
          {children}
        </WalletProvider>
      </body>
    </html>
  );
}
